name: Setup .NET SDK

on:
  workflow_dispatch:

jobs:
  setup-dotnet:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: 6.0.0

      - name: Verify .NET installation
        run: |
          dotnet --version
          dotnet --info